name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      bench_name:
        description: 'The name of the benchmark'
        required: false
        default: 'smol-song'
      dataset_path:
        description: 'The dataset path (remote)'
        required: false
        default: 'https://s3.blabla.com'

jobs:
  run-benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: skip step
        if: github.event == 'schedule'
        run: echo 'lol'
  
  next-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'OK'
